import {setBands,setState} from './face.js';
let context,analyser,source,stream,recorder,chunks=[],animation;
function attach(node){context ||= new AudioContext();if(source)source.disconnect();if(analyser)analyser.disconnect();analyser=context.createAnalyser();analyser.fftSize=1024;node.connect(analyser);analyser.connect(context.destination);const values=new Uint8Array(analyser.frequencyBinCount);
 cancelAnimationFrame(animation);function tick(){analyser.getByteFrequencyData(values);const avg=(start,end)=>{let sum=0;for(let i=start;i<end;i++)sum+=values[i];return sum/(end-start)/255};setBands({bass:avg(1,18),mid:avg(18,100),high:avg(100,300)});animation=requestAnimationFrame(tick)}tick()}
export async function record(button,onText){if(recorder?.state==='recording'){recorder.stop();button.textContent='MIC';return}
 context ||= new AudioContext();await context.resume();stream=await navigator.mediaDevices.getUserMedia({audio:true});
 const mic=context.createMediaStreamSource(stream);source=mic;analyser=context.createAnalyser();analyser.fftSize=1024;mic.connect(analyser);
 const values=new Uint8Array(analyser.frequencyBinCount);function tick(){analyser.getByteFrequencyData(values);let sum=0;for(let i=0;i<70;i++)sum+=values[i];setBands({bass:sum/(70*255),mid:sum/(100*255),high:sum/(150*255)});animation=requestAnimationFrame(tick)}cancelAnimationFrame(animation);tick();
 const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4','audio/ogg'].find(x=>MediaRecorder.isTypeSupported(x));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:{});chunks=[];
 recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=async()=>{stream.getTracks().forEach(x=>x.stop());cancelAnimationFrame(animation);setBands({bass:0,mid:0,high:0});setState('transcribing');const blob=new Blob(chunks,{type:recorder.mimeType});const form=new FormData();form.append('file',blob,'recording.'+(blob.type.includes('ogg')?'ogg':blob.type.includes('mp4')?'mp4':'webm'));
 try{const response=await fetch('/api/stt',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw Error(data.detail||'Transcription failed');onText(data.text);setState('idle')}catch(e){onText('',e.message);setState('error')}};
 recorder.start();button.textContent='STOP';setState('listening')}
export async function speak(text){const response=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:text.slice(0,2000)})});if(!response.ok){const data=await response.json();throw Error(data.detail||'Speech failed')}
 const bytes=await response.arrayBuffer();context ||= new AudioContext();await context.resume();const buffer=await context.decodeAudioData(bytes);const player=context.createBufferSource();player.buffer=buffer;source=player;attach(player);setState('speaking');player.start();return new Promise(resolve=>{player.onended=()=>{cancelAnimationFrame(animation);setBands({bass:0,mid:0,high:0});setState('idle');resolve()}})}
